name: release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

permissions:  # Set permissions for the GITHUB_TOKEN
  contents: write  # Grant write permission to contents
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
    steps:
    - uses: actions/checkout@v4
    - name: build binary
      run: |
        echo "that" > pgcli-linux-x86_64.exe
        chmod +x pgcli-linux-x86_64.exe
    #  run: bash -x script-in-docker.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pgcli-linux-x86_64.exe
        path: pgcli-linux-x86_64.exe
  create-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        body: "Release notes or description"
        draft: true
        prerelease: true 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: list
      run: ls -ll
    - name: upload build artifact to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
           ${{ github.workspace }}/pgcli-linux-x86_64.exe/*.exe
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
