name: release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

permissions:  # Set permissions for the GITHUB_TOKEN
  contents: write  # Grant write permission to contents
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
    steps:
    - uses: actions/checkout@v4
    - name: build binary
      run: |
         echo "this" > pgcli-Linux-x86_64.exe
      #run: bash -x script-in-docker.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pgcli-static-linux-x86_64
        path: pgcli-Linux-x86_64.exe
    
